//go:build docs
// +build docs

/*
 * knoxite
 *     Copyright (c) 2016-2021, Christian Muehlhaeuser <muesli@gmail.com>
 *     Copyright (c) 2020-2021, Nicolas Martin <penguwin@penguwin.eu>
 *     Copyright (c) 2021,      Raschaad Yassine
 *
 *   For license see LICENSE
 */

package main

import (
	"fmt"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

var (
	docsCmd = &cobra.Command{
		Use:    "docs [directory]",
		Short:  "Generates docs",
		Long:   `Generates documentation as manpages to the given directory path`,
		Hidden: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) != 1 {
				return fmt.Errorf("docs needs a target directory")
			}
			return generateDocs(args[0])
		},
	}
)

func init() {
	RootCmd.AddCommand(docsCmd)
}

func generateDocs(targetDirectory string) error {
	header := &doc.GenManHeader{
		Title:   "KNOXITE",
		Section: "1",
		Source:  "Auto generated by knoxite/knoxite",
	}

	return doc.GenManTree(RootCmd, header, targetDirectory)
}
